version: "3.8"

services:
  web:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env
    command: ["./wait-for-it.sh", "db", "--", "yarn", "prisma generate", "prisma migrate dev"]
    depends_on:
      - db

  db:
    image: postgres
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
